[build]
	command = "# no build command"
	functions = "functions"
	publish = "public"

[functions]
	directory= "functions"
	node_bundler = "esbuild"

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200
